import 'package:aicr_cli/src/finding/models/aicr_finding.dart';
import 'package:test/test.dart';

import 'package:aicr_cli/src/render/pr_comment_builder.dart';
import 'package:aicr_cli/src/report/aicr_report.dart';

void main() {
  group('PrCommentBuilder', () {
    test('snapshot-style test: given fixed report, body contains expected sections', () {
      final report = _makeReport(
        status: 'warn',
        pass: 4,
        warn: 2,
        fail: 0,
        findings: [
          const AicrFinding(
            id: 'det:1',
            category: AicrCategory.security,
            severity: AicrSeverity.warning,
            title: 'Avoid hardcoded secrets',
            messageTr: 'TR det 1',
            messageEn: 'EN det 1',
            sourceId: 'secret_rule',
            source: AicrFindingSource.deterministic,
          ),
          const AicrFinding(
            id: 'det:2',
            category: AicrCategory.testing,
            severity: AicrSeverity.warning,
            title: 'BLoC changes should include tests',
            messageTr: 'TR det 2',
            messageEn: 'EN det 2',
            sourceId: 'bloc_rule',
            source: AicrFindingSource.deterministic,
          ),
          const AicrFinding(
            id: 'ai:1',
            category: AicrCategory.dx,
            severity: AicrSeverity.suggestion,
            title: 'Consider adding documentation',
            messageTr: 'TR ai 1',
            messageEn: 'EN ai 1',
            sourceId: 'ai_fake',
            source: AicrFindingSource.ai,
            confidence: 0.75,
          ),
        ],
        aiEnabled: true,
        aiMode: 'fake',
        fileCount: 3,
        repoName: 'test-repo',
        runId: 'aicr_test123',
        diffHash: 'sha256:abcdef1234567890',
      );

      final body = PrCommentBuilder().build(report);

      // Header: repo, run id, AI mode
      expect(body, contains('**Repo:** test-repo'));
      expect(body, contains('**Run:** aicr_test123'));
      expect(body, contains('**AI:** ON (mode: fake)'));

      // Summary: risk level + confidence
      expect(body, contains('**Risk level:**'));
      expect(body, contains('**Overall confidence:**'));

      // CI info line
      expect(body, contains('**CI:** postComment=false · mode=update · marker=AICR_COMMENT'));

      // Tables: signals
      expect(body, contains('| Signal | Pass | Warn | Fail |'));
      expect(body, contains('| Deterministic | 4 | 2 | 0 |'));
      expect(body, contains('| AI (findings) | - | 1 | - |'));

      // Review recommended section
      expect(body, contains('### Review recommended'));
      expect(body, contains('🟨 **Recommended**'));

      // Top actions (limit 5)
      expect(body, contains('### Top actions'));
      expect(body, contains('Avoid hardcoded secrets'));
      expect(body, contains('BLoC changes should include tests'));
      expect(body, contains('Consider adding documentation'));

      // AI findings section
      expect(body, contains('### AI findings'));
      expect(body, contains('**dx**'));
      expect(body, contains('Consider adding documentation'));
      expect(body, contains('[ai,75%]'));

      // Deterministic findings section (grouped)
      expect(body, contains('### Deterministic findings'));
      expect(body, contains('**security**'));
      expect(body, contains('Avoid hardcoded secrets'));
      expect(body, contains('[det]'));
      expect(body, contains('**testing**'));
      expect(body, contains('BLoC changes should include tests'));

      // Footer: diff hash + generated by AICR
      expect(body, contains('**Diff hash:** `sha256:abcde`'));
      expect(body, contains('Generated by AICR'));

      // Ensure sections appear in correct order
      final headerIndex = body.indexOf('**Repo:**');
      final signalsIndex = body.indexOf('| Signal |');
      final reviewIndex = body.indexOf('### Review recommended');
      final topActionsIndex = body.indexOf('### Top actions');
      final aiFindingsIndex = body.indexOf('### AI findings');
      final detFindingsIndex = body.indexOf('### Deterministic findings');
      final footerIndex = body.indexOf('**Diff hash:**');

      expect(headerIndex, lessThan(signalsIndex));
      expect(signalsIndex, lessThan(reviewIndex));
      expect(reviewIndex, lessThan(topActionsIndex));
      expect(topActionsIndex, lessThan(aiFindingsIndex));
      expect(aiFindingsIndex, lessThan(detFindingsIndex));
      expect(detFindingsIndex, lessThan(footerIndex));
    });

    test('renders correctly when no AI findings', () {
      final report = _makeReport(
        status: 'warn',
        pass: 5,
        warn: 1,
        fail: 0,
        findings: [
          const AicrFinding(
            id: 'det:1',
            category: AicrCategory.security,
            severity: AicrSeverity.warning,
            title: 'Security issue',
            messageTr: 'TR',
            messageEn: 'EN',
            sourceId: 'security_rule',
            source: AicrFindingSource.deterministic,
          ),
        ],
        aiEnabled: false,
        aiMode: 'noop',
        fileCount: 2,
        repoName: 'test-repo',
        runId: 'aicr_test',
        diffHash: 'sha256:abc123',
      );

      final body = PrCommentBuilder().build(report);

      // Should not have AI findings section
      expect(body, isNot(contains('### AI findings')));

      // Should have deterministic findings
      expect(body, contains('### Deterministic findings'));
      expect(body, contains('Security issue'));
    });

    test('renders correctly when no deterministic findings', () {
      final report = _makeReport(
        status: 'pass',
        pass: 6,
        warn: 0,
        fail: 0,
        findings: [
          const AicrFinding(
            id: 'ai:1',
            category: AicrCategory.quality,
            severity: AicrSeverity.suggestion,
            title: 'AI suggestion',
            messageTr: 'TR',
            messageEn: 'EN',
            sourceId: 'ai_fake',
            source: AicrFindingSource.ai,
            confidence: 0.8,
          ),
        ],
        aiEnabled: true,
        aiMode: 'fake',
        fileCount: 1,
        repoName: 'test-repo',
        runId: 'aicr_test',
        diffHash: 'sha256:abc123',
      );

      final body = PrCommentBuilder().build(report);

      // Should have AI findings
      expect(body, contains('### AI findings'));
      expect(body, contains('AI suggestion'));

      // Should not have deterministic findings section
      expect(body, isNot(contains('### Deterministic findings')));
    });

    test('renders correctly when no findings at all', () {
      final report = _makeReport(
        status: 'pass',
        pass: 6,
        warn: 0,
        fail: 0,
        findings: const [],
        aiEnabled: false,
        aiMode: 'noop',
        fileCount: 1,
        repoName: 'test-repo',
        runId: 'aicr_test',
        diffHash: 'sha256:abc123',
      );

      final body = PrCommentBuilder().build(report);

      // Should not have findings sections
      expect(body, isNot(contains('### AI findings')));
      expect(body, isNot(contains('### Deterministic findings')));
      expect(body, isNot(contains('### Top actions')));

      // Should have review recommended
      expect(body, contains('### Review recommended'));
      expect(body, contains('🟩 **Not needed**'));
    });

    test('ensures stable ordering - same report produces same output', () {
      final report = _makeReport(
        status: 'warn',
        pass: 4,
        warn: 2,
        fail: 0,
        findings: [
          const AicrFinding(
            id: 'det:2',
            category: AicrCategory.testing,
            severity: AicrSeverity.warning,
            title: 'BLoC changes should include tests',
            messageTr: 'TR',
            messageEn: 'EN',
            sourceId: 'bloc_rule',
            source: AicrFindingSource.deterministic,
          ),
          const AicrFinding(
            id: 'det:1',
            category: AicrCategory.security,
            severity: AicrSeverity.warning,
            title: 'Avoid hardcoded secrets',
            messageTr: 'TR',
            messageEn: 'EN',
            sourceId: 'secret_rule',
            source: AicrFindingSource.deterministic,
          ),
          const AicrFinding(
            id: 'ai:1',
            category: AicrCategory.dx,
            severity: AicrSeverity.suggestion,
            title: 'Consider adding documentation',
            messageTr: 'TR',
            messageEn: 'EN',
            sourceId: 'ai_fake',
            source: AicrFindingSource.ai,
            confidence: 0.75,
          ),
        ],
        aiEnabled: true,
        aiMode: 'fake',
        fileCount: 3,
        repoName: 'test-repo',
        runId: 'aicr_test',
        diffHash: 'sha256:abc123',
      );

      final body1 = PrCommentBuilder().build(report);
      final body2 = PrCommentBuilder().build(report);

      // Same report should produce identical output
      expect(body1, equals(body2));
    });
  });
}

AicrReport _makeReport({
  required String status,
  required int pass,
  required int warn,
  required int fail,
  required List<AicrFinding> findings,
  required bool aiEnabled,
  String aiMode = 'noop',
  required int fileCount,
  required String repoName,
  required String runId,
  required String diffHash,
}) {
  final meta = Meta.fromFlat(
    toolVersion: '0.1.0',
    runId: runId,
    createdAt: '2025-01-01T00:00:00.000Z',
    repoName: repoName,
    aiEnabled: aiEnabled,
    aiMode: aiMode,
    diffHash: diffHash,
    fileCount: fileCount,
  );

  final summary = Summary.fromStringStatus(
    status: status,
    ruleResults: Counts(pass: pass, warn: warn, fail: fail),
    contractResults: Counts(pass: 0, warn: 0, fail: 0),
    fileFindings: FileCounts(info: 0, warn: 0, error: 0),
  );

  return AicrReport(
    meta: meta,
    summary: summary,
    rules: const [],
    findings: findings,
    contracts: const [],
    files: const [],
    recommendations: const [],
    aiReview: null,
  );
}

